### ISSUE TITLE
Create a health check dashboard section

### ISSUE THREAD

**Issue by ChiuchiuSorin** [xwikisas/application-admintools#13]
On the Admin Tools main dashboard there should be a section for starting a health check of your instance.
It could start with only some checks, like encoding, memory config, and have it extended in the future

**Comment by oanalavinia** [comment]
Here is a proposal done by our designer for the health check section. It's just a concept, since there will be many things changed depending on what can be implemented
![image](https://github.com/xwikisas/application-admintools/assets/22794181/58df3cb6-303d-46fb-9b14-81736b15170e)
