### ISSUE TITLE
Admin user can install it but not use

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-admintools#45]
Being logged as Admin after installing the RC version of this pro app and obtaining trial license, I can't use it properly - I see some velocity codes and error on "AdminTools.WebHome"

![image](https://github.com/xwikisas/application-admintools/assets/56109799/a5ae58f9-c3ba-4f46-8281-d5f6f057e0b5)

However, if I enable superadmin account and login with it, app is usable
![image](https://github.com/xwikisas/application-admintools/assets/56109799/8c55a8ea-c002-4339-bb4e-f3b5828bd8e9)

**Comment by ChiuchiuSorin** [comment]
Did you test it on jetty or Tomcat?

**Comment by petrenkonikita112263** [comment]
Logs for Admin

```
2024-02-28 11:25:35,483 [http-nio-7635-exec-5 - http://localhost:7635/xwiki/bin/view/AdminTools/] WARN  c.x.x.XWiki - Error on too many recursive includes for topic AdminTools.Code.Macros
2024-02-28 11:25:35,557 [http-nio-7635-exec-5 - http://localhost:7635/xwiki/bin/view/AdminTools/] WARN  c.x.x.XWiki - Error on too many recursive includes for topic AdminTools.Code.Macros
```

**Comment by petrenkonikita112263** [comment]
@ChiuchiuSorin you can see from screen it's Tomcat servlet

**Comment by ChiuchiuSorin** [comment]
It does not reproduce to me. Could you give me more info about the used environment?

**Comment by petrenkonikita112263** [comment]
Here's the entire log of issue

**Comment by petrenkonikita112263** [comment]
I upgraded my XWiki on Tomcat servlet with PostgreSQL this week from 16.1-RC to 16.1.0 (before it's 16.0). I haven't changed the permanent directory path, I only backup my configuration files with hibernate (to prevent overwriting them during the upgrade). I installed Admin Tools (Pro) there were no errors or warning in install logs from EM.

**Comment by ChiuchiuSorin** [comment]
I did try with different users: the default Admin created at installation and user added to the admin group and it does not reproduce. I will check with Lavinia to see her opinion on this.

**Comment by petrenkonikita112263** [comment]
Confirm I can't reproduce after uninstall app with its dependency License app, and install again. Before it I had License app (without any pro app installed alongside)

![image](https://github.com/xwikisas/application-admintools/assets/56109799/e7b13d5f-efee-4590-937f-e5fccb347f14)

**Comment by ChiuchiuSorin** [comment]
Alright. Could you please check if #46 it still reproduces?
