### ISSUE TITLE
Guest can see the home page of app with velocity errors

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-admintools#46]
After installing a pro app and obtaining trial license, navigate on the home page "AdminTools.WebHome", logout from XWiki and see the content of a page 

![HFBmeYckWlTHBRsjXLzuUBuw](https://github.com/xwikisas/application-admintools/assets/56109799/c34326d6-5353-42ba-8673-a6c5a7799049)

**Comment by ChiuchiuSorin** [comment]
Same as in #45, I could not reproduce: https://up1.xwikisas.com/#c0NDNEpMyt1dBLGLnWn2oQ

**Comment by petrenkonikita112263** [comment]
I uninstalled and installed the app as I did here https://github.com/xwikisas/application-admintools/issues/45#issuecomment-1968990477. I have latest License app and Admin Tools app, but still, guests see velocity errors

![image](https://github.com/xwikisas/application-admintools/assets/56109799/d336b129-2815-4bce-9726-3844fd145f04)
