### ISSUE TITLE
The Security configuration URL from the Help Links page leads to the wrong page

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-admintools#59]
By opening http://localhost:port/xwiki/bin/view/AdminTools/HelpLinks page and selecting items _[Security configuration](https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Configuration/Encoding/)_ it leads to Encoding page that seems not appropriate. Perhaps _[Security](https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Security)_ should be the expected page.

**Comment by ChiuchiuSorin** [comment]
Will modify the name from `Security configuration` to `Encoding configuration`.
