### ISSUE TITLE
Page Help links include only useful URLs for MySQL as supported database

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-admintools#60]
In the heading **Database issues**, the first links mentioned supported database and its installation. Then, 3 and 4 items in that list said only MySQL database. 

Is it intended to list MySQL and not other DBs? Don't you think it's duplication of already mentioned _[Specififc databases instructions](https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Installation/InstallationWAR/#HSpecificdatabasesinstructions)_. If not, shouldn't the mention of MySQL and the following databases Oracle, PostgreSQL, MariaDB be nested listed?

Like

- Specific databases instructions
  - MySQL installation guide
  - MySQL Troubleshooting
  - PostgreSQL installation guide
  - PostgreSQL Troubleshooting
  - ....

**Comment by ChiuchiuSorin** [comment]
From what I understood, MySQL is the most commonly used database for XWiki, which is why I've included direct instructions for it. If you consider there is no need for additional links, I'd prefer to remove the MySQL instructions entirely to avoid cluttering the page.

**Comment by petrenkonikita112263** [comment]
> I'd prefer to remove the MySQL instructions entirely to avoid cluttering the page.

Agree with it, considering that having XWiki with this pro app - indicates that the user has and uses one of the supported databases.
