### ISSUE TITLE
Gather info about the wiki size

### ISSUE THREAD

**Issue by ChiuchiuSorin** [xwikisas/application-admintools#7]
A new `Instance usage` section should be added to include info about number of wikis, of documents, users composition from main wiki or subwikis.

This will use the [Active Installs 2](https://extensions.xwiki.org/xwiki/bin/view/Extension/Active%20Installs%202%20API/) API, so other things could be included later.

**Comment by oanalavinia** [comment]
A mockup for this section has been done by our designer. Note that only the `main numbers` section will be done as part of this issue
![image](https://github.com/xwikisas/application-admintools/assets/22794181/051859e0-6895-4219-a03f-8258c8312b8f)
