### ISSUE TITLE
Add the option to restart the XWiki instance

### ISSUE THREAD

**Issue by ChiuchiuSorin** [xwikisas/application-admintools#79]
in order to apply a patch, we need the option to trigger the restart of the XWiki instance.

**Comment by oanat** [comment]
I believe we also need a start of the XWiki instance since just stopping does not make sense (see #81)

**Comment by vmassol** [comment]
I'm curious to know how you'd implement this since it depends a lot on the XWiki distribution used. We'd love to implement the ability to upgrade XWiki (which is basically a restart) but we haven't found a solution that works for all distributions.

**Comment by ChiuchiuSorin** [comment]
After discussing with @mflorea and @oanalavinia, we came to the conclusion that this functionality is not yet viable, as the restart option is specific to every servlet engine and not fully supported by XWiki (the instance does not work properly after a restart). Also a restart process might behave unexpected if it's done manually from within XWiki, as tomcat does not offer a direct API to redeploy a webapp.
