### ISSUE TITLE
Admin Tools config page remains in Administration after uninstall

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-admintools#99]
Steps to reproduce:

1. Click on Administer Wiki
2. Click on Extensions > Extensions > Installed Extensions
3. Search Admin Tools Application (Pro)
4. Click on Uninstall
5. Click on Continue

Expected results: The app is uninstalled and there is no configuration page in Administration anymore.

Actual results: The config page remains in Administration empty, with a Save button.

![AdminToolsUninstall](https://github.com/user-attachments/assets/fc314f9d-d8f1-40a8-8281-13d4f594be6c)

Environment: Cloud XWiki 15.10.8, Admin Tools Application (Pro) 1.0, Chrome 127, Windows 11 Pro

**Comment by petrenkonikita112263** [comment]
Note that this is caused by more root issue. As after uninstalling Admin Tools (Pro) you have a dependency "Admin Tools Application (Pro) - Default" and licensor app will print warning message that you have invalid license for this app.
